// Code generated by "stringer -type State -trimprefix State"; DO NOT EDIT.

package musig

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateUnknown-0]
	_ = x[StateNew-1]
	_ = x[StateCommit-2]
	_ = x[StateReveal-3]
	_ = x[StateCosign-4]
	_ = x[StateSign-5]
}

const _State_name = "UnknownNewCommitRevealCosignSign"

var _State_index = [...]uint8{0, 7, 10, 16, 22, 28, 32}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
